version: "3.8"
services:
  mc:
    image: ${DOCKER_IMAGE}:${BUILD_TAG}
    container_name: mc-paper-geyser
    ports:
      - "25566:25565"          # Java Edition TCP
      - "19132:19132/udp"      # Bedrock Edition UDP
      - "25581:8100"           # BlueMap Web Interface
    environment:
      TZ: "Europe/Athens"
      EULA: "true"
      TYPE: "PAPER"
      ONLINE_MODE: "false"
      OPS: "papa"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "admin"
      MODRINTH_PROJECTS: "authmereloaded,bluemap,skinsrestorer,essentialsx,luckperms,gsit,graves"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
    volumes:
      - ./data:/data           # Данные будут лежать в /opt/minecraft/data на хосте
      - ./scripts/auto-patch-authme.sh:/custom-init.d/auto-patch-authme.sh:ro
    restart: unless-stopped

  # Удобный веб-интерфейс для загрузки модов/плагинов и редактирования конфигов
  filebrowser:
    image: ${REGISTRY_IP}:5050/minecraft-filebrowser:${BUILD_TAG}
    container_name: mc-filebrowser
    user: "1000:1000"          # Совпадает с правами файлов майнкрафта
    ports:
      - "25580:80"             # Веб-интерфейс будет доступен на порту 25580
    volumes:
      - ./data:/srv            # Открываем доступ к папке майнкрафта
      - filebrowser_db:/database
    environment:
      - TZ=Europe/Athens
      - FB_DATABASE=/database/filebrowser.db
    restart: unless-stopped

volumes:
  filebrowser_db:
  # Шаблон для ванильного сервера (при необходимости можно запустить параллельно на другом порту или вместо основного)
  # mc-vanilla:
  #   image: itzg/minecraft-server:latest
  #   container_name: mc-vanilla
  #   ports:
  #     - "25566:25565"
  #   environment:
  #     EULA: "true"
  #     TYPE: "VANILLA"
  #     VERSION: "LATEST"
  #   volumes:
  #     - ./vanilla-data:/data
  #   restart: unless-stopped
