@Library('mylib@main') _

properties([
    parameters([
        booleanParam(name: 'DEPLOY_MONITOR_ONLY', defaultValue: false, description: 'Deploy ONLY warden-monitor without touching the Minecraft server')
    ])
])

// Override production server IP with game server IP for deployment
env.PROD_SERVER_IP = env.GAME_SERVER_IP ?: '192.168.0.220'

// Configure target node for deployment
node('built-in') {
    // Fix root-owned files generated by Docker in previous builds so that git checkout can succeed
    sh 'docker run --rm -v "${WORKSPACE}:/workspace" maven:3.9-eclipse-temurin-21 chown -R $(id -u):$(id -g) /workspace || true'
    checkout scm

    stage('Build Plugins') {
        // Запуск локального скрипта сборки плагина. Он сам проверит версию и пропустит сборку, если JAR уже есть.
        sh 'bash scripts/build-warden.sh'
    }

    stage('Prepare Server Scripts') {
        sshagent(credentials: [env.SERVER_USER]) {
            sh """
            ssh -o StrictHostKeyChecking=no ${env.SERVER_USER}@${env.PROD_SERVER_IP} '
            # Create scripts directory on target server and set permissions
            sudo mkdir -p /opt/minecraft/scripts
            sudo chown -R \$(whoami) /opt/minecraft/scripts
            # Remove old scripts to prevent "Text file busy" error during scp if they are running
            # Use rm -rf because Docker might have accidentally created it as a directory if it was missing during startup
            rm -rf /opt/minecraft/scripts/*.sh
            mkdir -p /opt/minecraft/warden-monitor
            mkdir -p /opt/minecraft/data/plugins/WardenLog
            sudo chown -R \$(whoami) /opt/minecraft/data/plugins/WardenLog
            '
            
            # Force copy scripts and warden-monitor from repository to server
            scp -o StrictHostKeyChecking=no -r scripts/* ${env.SERVER_USER}@${env.PROD_SERVER_IP}:/opt/minecraft/scripts/
            scp -o StrictHostKeyChecking=no -r warden-monitor/* ${env.SERVER_USER}@${env.PROD_SERVER_IP}:/opt/minecraft/warden-monitor/
            scp -o StrictHostKeyChecking=no data/plugins/*.jar ${env.SERVER_USER}@${env.PROD_SERVER_IP}:/opt/minecraft/data/plugins/
            
            # Make scripts executable
            ssh -o StrictHostKeyChecking=no ${env.SERVER_USER}@${env.PROD_SERVER_IP} 'chmod +x /opt/minecraft/scripts/*.sh'
            """
        }
    }
    if (params.DEPLOY_MONITOR_ONLY) {
        stage('Deploy Monitor Only') {
            sshagent(credentials: [env.SERVER_USER]) {
                sh """
                scp -o StrictHostKeyChecking=no docker-compose.yml ${env.SERVER_USER}@${env.PROD_SERVER_IP}:/opt/minecraft/docker-compose.yml
                ssh -o StrictHostKeyChecking=no ${env.SERVER_USER}@${env.PROD_SERVER_IP} 'cd /opt/minecraft && docker compose up -d warden-monitor'
                """
            }
        }
    }
}

if (!params.DEPLOY_MONITOR_ONLY) {
    declarativePipeline(agent: 'built-in')
}
