service_name: "minecraft"
stack_type: "docker-compose"
target_cluster: "prod"

# Указываем конкретную директорию для публикации
deploy:
  dir: "/opt/minecraft"


volumes:
  data: "/opt/minecraft/data"

containers:
  - "mc-paper-geyser"

migrations: false
